### ISSUE TITLE
旧nomnichi_railsを参考に静的ページをrenderする仕組みを作成

### ISSUE THREAD

**Issue by emiksk** [nomlab/nomnichi#1]
旧nomnichi_railsを参考に静的ページをrenderする仕組みを作成する

**Comment by kobayashi1027** [comment]
旧nomnichi_railsを参考に，動的ページのレイアウトを適用しつつ静的ページをrenderする仕組みを実装した．
行ったことは以下の通りである．

1. app/controller/application_controller.rbに`rescue_404`というpublic_htmlディレクトリ以下の静的ページをrenderするメソッドを作成
2. config/routes.rbの最後に`get '*path', to: 'application#rescue_404'`と記述し，どのルーティングにもマッチしないgetリクエスト(静的ページのgetリクエスト)があった場合，`rescue_404`を呼び出すように設定
3. publicをpublic_htmlにリネーム

publicディレクトリ以下に静的ページがある場合，2.のルーティングの評価がされず`rescue_404`が呼ばれないため，動的ページのレイアウトが適用されていない静的ページが表示されてしまう．
このため，3.を行い，publicディレクトリをなくした．

残された課題として，以下がある．
* public_html以下の不要なファイルの削除

**Comment by okada-takuya** [comment]
/members.htmlに初回アクセスした場合CSSが読み込まれない問題が発生することがある．リロードすると治る．

+ public_html以下の不要なファイルの削除
  リリース後に検討予定である．

静的ページをrenderする仕組みが作成できたため，closeする．
