### ISSUE TITLE
プレビュー機能が正しく動作しないバグについて対処

### ISSUE THREAD

**Issue by emiksk** [nomlab/nomnichi#4]
プレビュー機能が正しく動作しないバグについて対処する．

**Comment by okada-takuya** [comment]
JavascriptでGETリクエストを用いて記事本文を投げる際，リクエストのパラメータ長の制限に引っかかることがバグの原因であった．
そこで，RailsとのやりとりをPOSTで行うように変更したところ，バグが修正された．

**Comment by okada-takuya** [comment]
対象が完了したため，closeする．
