### ISSUE TITLE
showページのURLにpermalinkを使用

### ISSUE THREAD

**Issue by emiksk** [nomlab/nomnichi#5]
showページのURLにpermalinkを使用する．

**Comment by okada-takuya** [comment]
permalinkで記事にアクセス可能にした．
同時に，

+ パーマリンクの自動入力機能
+ パーマリンクのバリデーション
+ バリデーションにそぐわないパーマリンクの修正

を実施した．

Show以外のアクションには，:idでアクセスするようになっている．
なお，ユーザはこのURLを意識することはない．

**Comment by okada-takuya** [comment]
完了したため，closeする．
