### ISSUE TITLE
トップページ左上の岡大のシンボル画像が表示されない

### ISSUE THREAD

**Issue by sugi-k** [nomlab/nomnichi#54]
以下のアドレスでノムニチのトップページを閲覧すると，
左上の岡大の画像が表示されなくなる．
http://www.swlab.cs.okayama-u.ac.jp/lab/nom

以下のように末尾にスラッシュを付けると表示されます
http://www.swlab.cs.okayama-u.ac.jp/lab/nom/

**Comment by okada-takuya** [comment]
#57 のマージにより解決されたため close する．
