### ISSUE TITLE
記事削除リンクの追加と，削除リンクと編集リンクのアイコン化

### ISSUE THREAD

**Issue by date-taiki** [nomlab/nomnichi#55]
これまでのノムニチには記事を削除する機能がなかった．このため記事を削除できなかった．そこで，記事削除リンクの追加する．記事削除リンクはアイコンで表示する．これに伴い，編集リンクもアイコンで表示するように変更する．

**Comment by okada-takuya** [comment]
#56 のマージにより解決したため close する．
