### ISSUE TITLE
トップページのレイアウトを検討

### ISSUE THREAD

**Issue by emiksk** [nomlab/nomnichi#6]
トップページのレイアウトを検討

**Comment by yoshida564** [comment]
トップページのレイアウトを検討し，以下の4つを実装した．
(1) タイトルを追加した
(2) 研究室概要を追加した
(3) ノムニチ注目記事を追加した
(4) 岡山大学のロゴを追加した

今後の課題として，以下の2つがある．
(1) 明るく見えるような色の検討
(2) ロゴを透過画像に変更

**Comment by okada-takuya** [comment]
1. 明るく見えるような色の検討
   ひとまず今の色でいく
2. タイトルをトップページ以外にも表示させるか否かの検討
   表示させない方針である

検討が一通り終了したため，closeする．
