### ISSUE TITLE
ブログ一覧画面のレイアウトを検討，実装

### ISSUE THREAD

**Issue by emiksk** [nomlab/nomnichi#7]
ブログ一覧画面のレイアウトを検討，実装

**Comment by fujita-m** [comment]
ブログ一覧画面のレイアウトを検討した．
画面の左側に記事一覧，右側にサイドバーを配置している．
サイドバーの内容は以下の通りである．
(1) 記事の検索フォーム
(2) 新規コメント
(3) 年度，月毎の記事のアーカイブ

(1)について，フォームを用意しているのみであり，検索機能の実装はできていない．
(2)について，コメントされた記事名，コメント，コメント者名が表示されている．記事名は，記事へのリンクとなっている． 
(3)について，jquery tree viewを用いて実装している．これを用いることで，年度と月をtree状に配置し，表示と格納が可能になる．また，これらの要素はリンクとなっており，リンク先は，クリックした年度または月の記事一覧画面となっている．また，この導入にはrailsのsubmoduleを使用する必要がある．
この導入手順を以下に示す．
(A) $ git submodule init
(b) $ git submodule update

**Comment by ikeda-yuko** [comment]
次回までの課題を以下に示す．

* 検索フォームの有効化
* アーカイブの記事数をログイン時と非ログイン時で変える

**Comment by okada-takuya** [comment]
一覧画面の検討と実装が完了したため，一度closeする．

+ 検索フォーム有効化
+ アーカイブの記事数をログイン時と非ログイン時で変える

上記に関しては別途Issueを作成する．
