### ISSUE TITLE
記事に簡単に画像を貼り付けられるようにする

### ISSUE THREAD

**Issue by okada-takuya** [nomlab/nomnichi#81]
現在，記事に貼り付ける画像へのリンクはGoogle photoの公開アルバムから1つ1つ取得して貼り付けている．
これを，ノムニチの記事編集画面のタブの1つに画像一覧を実装し，そこからリンクを取り出せるようにすることで，簡単に画像を貼り付けられるようにする．

Associated to [AI0245](http://jay.swlab.cs.okayama-u.ac.jp/minutes/300?ai=0245) of minute 300. by @yoshida564 at 2016/09/16

**Comment by yoshida564** [comment]
Associate to [AI0245](http://jay.swlab.cs.okayama-u.ac.jp/minutes/300?ai=0245) of minute 300.
